const article=document.querySelector('#resource');
const escapeHtml=value=>String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
const text=(value,fallback='Not established')=>value===null||value===undefined||String(value).trim()===''?fallback:escapeHtml(value);
const list=(values)=>Array.isArray(values)&&values.length?values.join(' · '):'Not established';
const field=(label,value)=>`<dt>${label}</dt><dd>${value}</dd>`;
function safeLink(url,label){try{return new URL(url).protocol==='https:'?`<a href="${escapeHtml(url)}">${label}</a>`:label;}catch{return label;}}
function setPageMetadata(record){const pageUrl=new URL(`resource/${encodeURIComponent(record.id)}/`,location.href).href;let canonical=document.querySelector('link[rel="canonical"]');if(!canonical){canonical=document.createElement('link');canonical.rel='canonical';document.head.append(canonical);}canonical.href=pageUrl;let description=document.querySelector('meta[name="description"]');if(!description){description=document.createElement('meta');description.name='description';document.head.append(description);}description.content=record.description||'Source-backed details for a DaVinci Resolve resource.';}
function render(record){
 document.title=`${record.name} — Open Resolve List`;
 setPageMetadata(record);
 const requirements=record.requirements||{},version=record.version||{};
 const evidence=record.evidence||[];
 article.innerHTML=`<p class="eyebrow">${text(record.category)}</p><h1>${text(record.name)}</h1><p class="lede">${text(record.description)}</p><p>${safeLink(record.urls?.canonical||record.url,'Open original resource ↗')}</p><dl class="facts">${field('Creator',text(record.creator))}${field('Format',text(record.kind))}${field('Access',text(record.access))}${field('Platforms',list(record.platforms))}${field('Resolve edition',list(requirements.editions))}${field('Resolve version',requirements.resolve?.length?requirements.resolve.map(range=>[range.edition,range.min&&range.max&&range.min===range.max?range.min:[range.min||'Any',range.max||'Any'].join('–')].filter(Boolean).join(': ')).join(' · '):'Not established')}${field('Processing',text(requirements.processing))}${field('Tool version',version.version||version.kind||'Not established')}</dl><h2>Evidence</h2><p>${evidence.length} field-level source record${evidence.length===1?'':'s'}.</p>${evidence.length?`<ul>${evidence.map(item=>`<li><strong>${text(item.level)}</strong> — ${text(item.field)} · ${safeLink(item.source,'Source')}<br>${text(item.note,'No additional note.')}</li>`).join('')}</ul>`:'<p>No field-level evidence recorded.</p>'}<p class="muted">This page reports maintained source evidence; it does not imply blanket compatibility or installation testing.</p>`;
}
async function init(){try{const id=new URLSearchParams(location.search).get('id');if(!id)throw Error('Missing resource ID');const response=await fetch(`api/v1/resources/${encodeURIComponent(id)}.json?v=1`,{cache:'no-store'});if(!response.ok)throw Error(`HTTP ${response.status}`);const data=await response.json();const record=data.resource;if(!record||record.id!==id)throw Error('Resource not found');render(record);}catch(error){article.innerHTML='<h1>Resource unavailable</h1><p>Return to the catalogue and choose a current resource.</p>';console.error(error);}}
init();
